global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'password-gen-api'
    metrics_path: /prometheus
    static_configs:
      - targets: [ 'password-gen-api:8080' ]
