{
 "title": "Password Gen",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JVM Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"heap\"})",
     "legendFormat": "Max Heap"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"heap\"})",
     "legendFormat": "Committed Heap"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "sum(jvm_memory_used_bytes)", "legendFormat": "Used Heap" },
    { "expr": "sum(jvm_memory_max_bytes)", "legendFormat": "Max Heap" },
    {
     "expr": "sum(jvm_memory_committed_bytes)",
     "legendFormat": "Committed Heap"
    }
   ]
  },
  {
   "title": "JVM Live Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "Live Threads" }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "CPU Usage" }
   ]
  },
  {
   "title": "GC Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(jvm_gc_pause_seconds_count[1m])) * 60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max GC Pause Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (instance)(sum by (instance)(rate(jvm_gc_pause_seconds_sum[1m])) % sum by (instance)(rate(jvm_gc_pause_seconds_count[1m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Password Gen Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(password_generate_seconds_sum[30s]) / rate(password_generate_seconds_count[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Password Gen Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(password_generate_seconds_count[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}